const ROLE_ADMIN='ROLE_ADMIN'
const ROLE_CUSTOMER='ROLE_CUSTOMER'

const ROLES={
  [ROLE_ADMIN]:'Administrateur',
  [ROLE_CUSTOMER]:'Client',
}

const ISSUE_STATUS_NEW="ISSUE_STATUS_NEW"
const ISSUE_STATUS_OPEN="ISSUE_STATUS_OPEN"
const ISSUE_STATUS_IN_PROGRESS="ISSUE_STATUS_IN_PROGRESS"
const ISSUE_STATUS_CLOSED="ISSUE_STATUS_CLOSED"
const ISSUE_STATUS_REJECTED="ISSUE_STATUS_REJECTED"
const ISSUE_STATUS_INTERNAL_VALIDATION="ISSUE_STATUS_INTERNAL_VALIDATION"
const ISSUE_STATUS_INTERNAL_VALID="ISSUE_STATUS_INTERNAL_VALID"
const ISSUE_STATUS_CUSTOMER_VALIDATION="ISSUE_STATUS_CUSTOMER_VALIDATION"
const ISSUE_STATUS_CUSTOMER_VALID="ISSUE_STATUS_CUSTOMER_VALID"

const ISSUE_STATUS={
  [ISSUE_STATUS_NEW]:"Nouveau",
  [ISSUE_STATUS_OPEN]:"Ouvert",
  [ISSUE_STATUS_IN_PROGRESS]:"En développement",
  [ISSUE_STATUS_CLOSED]:"Fermé",
  [ISSUE_STATUS_REJECTED]:"Rejeté",
  [ISSUE_STATUS_INTERNAL_VALIDATION]:"Validation interne",
  [ISSUE_STATUS_INTERNAL_VALID]:"Validé interne",
  [ISSUE_STATUS_CUSTOMER_VALIDATION]:"Validaiton client",
  [ISSUE_STATUS_CUSTOMER_VALID]:"Validé client",
}

const ISSUE_BUG='ISSUE_BUG'
const ISSUE_ENHANCEMENT='ISSUE_ENHANCEMENT'

const ISSUE_KIND={
  [ISSUE_BUG]:'Bug',
  [ISSUE_ENHANCEMENT]:'Evolution',
}

const ISSUE_CATEGORY_UI="ISSUE_CATEGORY_UI"
const ISSUE_CATEGORY_REGISTRATION="ISSUE_CATEGORY_REGISTRATION"
const ISSUE_CATEGORY_PAYMENT="ISSUE_CATEGORY_PAYMENT"
const ISSUE_CATEGORY_DASHBOARD="ISSUE_CATEGORY_DASHBOARD"
const ISSUE_CATEGORY_PERFORMANCE="ISSUE_CATEGORY_PERFORMANCE"

const ISSUE_CATEGORY={
  [ISSUE_CATEGORY_UI]:"ui",
  [ISSUE_CATEGORY_REGISTRATION]:"registration",
  [ISSUE_CATEGORY_PAYMENT]:"payment",
  [ISSUE_CATEGORY_DASHBOARD]:"dashboard",
  [ISSUE_CATEGORY_PERFORMANCE]:"performance",
}

const ISSUE_PRIORITY_LOW="ISSUE_PRIORITY_LOW"
const ISSUE_PRIORITY_MEDIUM="ISSUE_PRIORITY_MEDIUM"
const ISSUE_PRIORITY_HIGH="ISSUE_PRIORITY_HIGH"
const ISSUE_PRIORITY_CRITICAL="ISSUE_PRIORITY_CRITICAL"

const ISSUE_PRIORITY={
  [ISSUE_PRIORITY_LOW]:"Basse",
  [ISSUE_PRIORITY_MEDIUM]:"Moyenne",
  [ISSUE_PRIORITY_HIGH]:"Haute",
  [ISSUE_PRIORITY_CRITICAL]:"Critique",
}

const PROJECT_ROLE_ADMIN="PROJECT_ROLE_ADMIN"
const PROJECT_ROLE_VALIDATOR="PROJECT_ROLE_VALIDATOR"
const PROJECT_ROLE_DEVELOPER="PROJECT_ROLE_DEVELOPER"

const PROJECT_ROLE={
  [PROJECT_ROLE_ADMIN]:"Administrateur",
  [PROJECT_ROLE_VALIDATOR]:"Valideur",
  [PROJECT_ROLE_DEVELOPER]:"Développeur",
}

module.exports={
 ROLES, ROLE_ADMIN,
 ISSUE_STATUS, ISSUE_KIND, ISSUE_CATEGORY, ISSUE_PRIORITY,
 PROJECT_ROLE
}
