const mongoose = require("mongoose")
const { schemaOptions } = require('../../../utils/schemas');
const { DUMMY_REF } = require("../../../utils/database");

const Schema = mongoose.Schema;

const MissionSchema = new Schema({
  application: {
    type: Schema.Types.ObjectId,
    ref: 'application',
    required: [true, `La candidature est obligatoire`],
  },
  customer: {
    type: Schema.Types.ObjectId,
    ref: 'application',
    required: [true, `Le client est obligatoire`],
  },
  freelance: {
    type: Schema.Types.ObjectId,
    ref: 'application',
    required: [true, `Le freelance est obligatoire`],
  },
  title: {
    type: String,
    required: [true,  `Le nom de mission est obligatoire`],
  },
  start_date: {
    type: Date,
    required: [true, `La date de début est obligatoire`],
  },
  end_date: {
    type: Date,
    required: [true, `La date de fin est obligatoire`],
  },
  // Total budget / somme des CRAs déclarés
  progress: {
    type: Number,
  },
  // TO_COME, CURRENT, FINISHED_FREELANCE (he declares), FINISHED_CUSTOMER (he validates), CLOSED
  status: {

  },
  // Reports generated by freelance (draft, sent, paid)
  reports: {

  }
}, schemaOptions
);

/* eslint-disable prefer-arrow-callback */
/* eslint-enable prefer-arrow-callback */


module.exports = MissionSchema;
