const DISCRIMINATOR_KEY = { discriminatorKey: 'type' }
const DISC_PARTNER='partner'
const DISC_MEMBER='member'
const DISC_ADMIN='admin'

const ROLE_ADMIN='ADMIN'
const ROLE_PARTNER='PARTNER'
const ROLE_MEMBER='MEMBER'
const ROLES={
    [ROLE_PARTNER] : 'Partenaire',
    [ROLE_MEMBER] : 'Membre',
    [ROLE_ADMIN] : 'Administrateur'
}

const CONTENT_TYPE_ARTICLE='ARTICLE'
const CONTENT_TYPE_GUIDE='GUIDE'
const CONTENT_TYPE_PODCAST='PODCAST'
const CONTENT_TYPE_VIDEO='VIDEO'
const CONTENT_TYPE={
    [CONTENT_TYPE_ARTICLE] : 'Article',
    [CONTENT_TYPE_VIDEO] : 'Vidéo',
    [CONTENT_TYPE_PODCAST] : 'Podcast',
    [CONTENT_TYPE_GUIDE] : 'Guide'
}

const SECTOR_PHARMA='PHARMA'
const SECTOR_INDUSTRY='INDUSTRY'
const SECTOR={
    [SECTOR_INDUSTRY]:'Industrie',
    [SECTOR_PHARMA]:'Pharmaceutique'
}

const CATEGORY_1='1'
const CATEGORY_2='2'
const CATEGORY={
    [CATEGORY_1]:'1',
    [CATEGORY_2]:'2',
}

const JOB_GENERAL_MANAGER = `GENERAL_MANAGER`
const JOB_DIGITAL_MANAGER = `DIGITAL_MANAGER`
const JOB_IT = `IT`
const JOB_FINANCIAL_MANAGER = `FINANCIAL_MANAGER`
const JOB_GENERAL_COUNSEL = `GENERAL_COUNSEL`
const JOB_COMMERCIIAL_MANAGER = `COMMERCIIAL_MANAGER`
const JOB_MARKETING_MANAGER = `MARKETING_MANAGER`
const JOB_STUDENT = `STUDENT`
const JOB_OTHER = `OTHER`

const JOBS={
    [JOB_GENERAL_MANAGER] : `Direction Générale`,
    [JOB_DIGITAL_MANAGER] : `Direction du digital`,
    [JOB_IT] : `Direction informatique`,
    [JOB_FINANCIAL_MANAGER] : `Direction financière`,
    [JOB_GENERAL_COUNSEL] : `Direction Juridique`,
    [JOB_COMMERCIIAL_MANAGER] : `Direction commerciale`,
    [JOB_MARKETING_MANAGER] : `Direction Marketing`,
    [JOB_STUDENT] : `Etudiant`,
    [JOB_OTHER] : `Autres`
}

module.exports={
    DISC_ADMIN,DISC_MEMBER,DISC_PARTNER, DISCRIMINATOR_KEY,
    ROLES, ROLE_ADMIN, ROLE_MEMBER, ROLE_PARTNER,
    CONTENT_TYPE, CONTENT_TYPE_ARTICLE, CONTENT_TYPE_GUIDE, CONTENT_TYPE_PODCAST, CONTENT_TYPE_VIDEO,
    SECTOR, SECTOR_INDUSTRY, SECTOR_PHARMA,
    CATEGORY, CATEGORY_1, CATEGORY_2,
    JOBS, JOB_GENERAL_MANAGER, JOB_DIGITAL_MANAGER, JOB_IT, JOB_FINANCIAL_MANAGER, JOB_GENERAL_COUNSEL, JOB_COMMERCIIAL_MANAGER, JOB_MARKETING_MANAGER, JOB_STUDENT, JOB_OTHER,
}