const DISCRIMINATOR_KEY = { discriminatorKey: 'type' }
const DISC_PARTNER = 'partner'
const DISC_MEMBER = 'member'
const DISC_ADMIN = 'admin'

const ROLE_ADMIN = 'ROLE_ADMIN'
const ROLE_PARTNER = 'ROLE_PARTNER'
const ROLE_MEMBER = 'ROLE_MEMBER'
const ROLES = {
  [ROLE_PARTNER]: 'Partenaire',
  [ROLE_MEMBER]: 'Membre',
  [ROLE_ADMIN]: 'Administrateur'
}

const CONTENT_TYPE_ARTICLE = 'CONTENT_TYPE_ARTICLE'
const CONTENT_TYPE_GUIDE = 'CONTENT_TYPE_GUIDE'
const CONTENT_TYPE_PODCAST = 'CONTENT_TYPE_PODCAST'
const CONTENT_TYPE_VIDEO = 'CONTENT_TYPE_VIDEO'
const CONTENT_TYPE = {
  [CONTENT_TYPE_ARTICLE]: 'Article',
  [CONTENT_TYPE_VIDEO]: 'Vidéo',
  [CONTENT_TYPE_PODCAST]: 'Podcast',
  [CONTENT_TYPE_GUIDE]: 'Guide'
}

const SECTOR_AERONAUTICS = `SECTOR_AERONAUTICS`
const SECTOR_AGRI_FOOD = `SECTOR_AGRI_FOOD`
const SECTOR_AUTOMOBILE = `SECTOR_AUTOMOBILE`
const SECTOR_OTHER = `SECTOR_OTHER`
const SECTOR_BIOTECHNOLOGIES = `SECTOR_BIOTECHNOLOGIES`
const SECTOR_BTP = `SECTOR_BTP`
const SECTOR_DESIGN_OFFICE = `SECTOR_DESIGN_OFFICE`
const SECTOR_CHEMISTRY = `SECTOR_CHEMISTRY`
const SECTOR_TRADE = `SECTOR_TRADE`
const SECTOR_COMMUNICATION = `SECTOR_COMMUNICATION`
const SECTOR_ACCOUNTING = `SECTOR_ACCOUNTING`
const SECTOR_AUDIT = `SECTOR_AUDIT`
const SECTOR_DEFENSE = `SECTOR_DEFENSE`
const SECTOR_ELECTRONICS = `SECTOR_ELECTRONICS`
const SECTOR_ENERGY = `SECTOR_ENERGY`
const SECTOR_TEACHING = `SECTOR_TEACHING`
const SECTOR_ENVIRONMENT = `SECTOR_ENVIRONMENT`
const SECTOR_ESN = `SECTOR_ESN`
const SECTOR_FINANCE = `SECTOR_FINANCE`
const SECTOR_IT = `SECTOR_IT`
const SECTOR_LOGISTICS = `SECTOR_LOGISTICS`
const SECTOR_METALLURGY = `SECTOR_METALLURGY`
const SECTOR_RESEARCH = `SECTOR_RESEARCH`
const SECTOR_HEALTH = `SECTOR_HEALTH`
const SECTOR_PUBLIC = `SECTOR_PUBLIC`
const SECTOR_TEXTILE = `SECTOR_TEXTILE`
const SECTOR_SPORT = `SECTOR_SPORT`

const SECTOR = {
  [SECTOR_AERONAUTICS] : `Aéronautique`,
  [SECTOR_AGRI_FOOD] : `Agroalimentaire`,
  [SECTOR_AUTOMOBILE] : `Automobile`,
  [SECTOR_OTHER] : `Autres industries`,
  [SECTOR_BIOTECHNOLOGIES] : `Biotechnologies`,
  [SECTOR_BTP] : `BTP & construction`,
  [SECTOR_DESIGN_OFFICE] : `Bureau d'études`,
  [SECTOR_CHEMISTRY] : `Chimie, cosmétique`,
  [SECTOR_TRADE] : `Commerce et distribution`,
  [SECTOR_COMMUNICATION] : `Communication et marketing`,
  [SECTOR_ACCOUNTING] : `Comptabilité, gestion et ressources humaines`,
  [SECTOR_AUDIT] : `Conseil & audit`,
  [SECTOR_DEFENSE] : `Défense et spatial`,
  [SECTOR_ELECTRONICS] : `Electronique`,
  [SECTOR_ENERGY] : `Energie`,
  [SECTOR_TEACHING] : `Enseignement et formation`,
  [SECTOR_ENVIRONMENT] : `Environnement`,
  [SECTOR_ESN] : `ESN`,
  [SECTOR_FINANCE] : `Finance, banque et assurance`,
  [SECTOR_IT] : `Informatique, internet et communication`,
  [SECTOR_LOGISTICS] : `Logistique et transport`,
  [SECTOR_METALLURGY] : `Métallurgie`,
  [SECTOR_RESEARCH] : `Recherche`,
  [SECTOR_HEALTH] : `Santé, Pharma`,
  [SECTOR_PUBLIC] : `Secteur public & collectivités`,
  [SECTOR_TEXTILE] : `Textile`,
  [SECTOR_SPORT] : `Sport`
}

const CATEGORY_THREAT_ANALYSIS = 'CATEGORY_THREAT_ANALYSIS'
const CATEGORY_NETWORK_SECURITY = 'CATEGORY_NETWORK_SECURITY'
const CATEGORY_CRYPTOGRAPHY = 'CATEGORY_CRYPTOGRAPHY'
const CATEGORY_APP_SECURITY = 'CATEGORY_APP_SECURITY'
const CATEGORY_FORENSIC = 'CATEGORY_FORENSIC'
const CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT = 'CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT'
const CATEGORY_CONFORMITY_AND_CONTROL = 'CATEGORY_CONFORMITY_AND_CONTROL'
const CATEGORY_CLOUD_SECURITY = 'CATEGORY_CLOUD_SECURITY'
const CATEGORY_SYSTEM_SECURITY = 'CATEGORY_SYSTEM_SECURITY'
const CATEGORY_SENSITIZATION_AND_FORMATION = 'CATEGORY_SENSITIZATION_AND_FORMATION'
const CATEGORY_EMERGING_SAFETY_TECHNOLOGIES = 'CATEGORY_EMERGING_SAFETY_TECHNOLOGIES'
const CATEGORY_INCIDENT_MANAGEMENT = 'CATEGORY_INCIDENT_MANAGEMENT'
const CATEGORY_SECURITY_POLICY_DESIGN = 'CATEGORY_SECURITY_POLICY_DESIGN'
const CATEGORY_ICS_SCADA = 'CATEGORY_ICS_SCADA'
const CATEGORY_EVENT_AND_COMMUNITY = 'CATEGORY_EVENT_AND_COMMUNITY'
const CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT_ADVANCED = 'CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT_ADVANCED'
const CATEGORY_ENDPOINTS_SECURITY = 'CATEGORY_ENDPOINTS_SECURITY'
const CATEGORY_DATA_SECURITY = 'CATEGORY_DATA_SECURITY'
const CATEGORY_NETWORK_SECURITY_ADVANCED = 'CATEGORY_NETWORK_SECURITY_ADVANCED'
const CATEGORY_SYSTEM_ARCHITECTURE_SECURITY = 'CATEGORY_SYSTEM_ARCHITECTURE_SECURITY'
const CATEGORY_INTERNAL_THREAT_PROTECTION ='CATEGORY_INTERNAL_THREAT_PROTECTION'
const CATEGORY_CRISIS_MANAGEMENT = 'CATEGORY_CRISIS_MANAGEMENT'
const CATEGORY_APP_AND_DEVOPS_SECURITY = 'CATEGORY_APP_AND_DEVOPS_SECURITY'
const CATEGORY_CLOUD_AND_VIRTUAL_ENVIRONMENT_SECURITY = 'CATEGORY_CLOUD_AND_VIRTUAL_ENVIRONMENT_SECURITY'
const CATEGORY_COMPLIANCE_MANAGEMENT = 'CATEGORY_COMPLIANCE_MANAGEMENT'
const CATEGORY_ATD_ATR = 'CATEGORY_ATD_ATR'
const CATEGORY_SOCIAL_NETWORK_AND_REPUTATION_SECURITY = 'CATEGORY_SOCIAL_NETWORK_AND_REPUTATION_SECURITY'
const CATEGORY_FINANCIAL_SECURITY = 'CATEGORY_FINANCIAL_SECURITY'
const CATEGORY_R_AND_D_SECURITY = 'CATEGORY_R_AND_D_SECURITY'
const CATEGORIES = {
  [CATEGORY_THREAT_ANALYSIS] : 'Analyse des Menaces et Intelligence',
  [CATEGORY_NETWORK_SECURITY] : 'Sécurité des Réseaux',
  [CATEGORY_CRYPTOGRAPHY] : 'Cryptographie',
  [CATEGORY_APP_SECURITY] : 'Sécurité des Applications',
  [CATEGORY_FORENSIC] :'Forensique Numérique',
  [CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT] : 'Gestion des Identités et des Accès',
  [CATEGORY_CONFORMITY_AND_CONTROL] : 'Conformité et Réglementation',
  [CATEGORY_CLOUD_SECURITY] : 'Sécurité Cloud',
  [CATEGORY_SYSTEM_SECURITY] : 'Sécurité des Systèmes',
  [CATEGORY_SENSITIZATION_AND_FORMATION] : 'Formation et Sensibilisation',
  [CATEGORY_EMERGING_SAFETY_TECHNOLOGIES] : 'Technologies de Sécurité Émergentes',
  [CATEGORY_INCIDENT_MANAGEMENT] : 'Gestion des Incidents',
  [CATEGORY_SECURITY_POLICY_DESIGN] : 'Conception de Politiques de Sécurité',
  [CATEGORY_ICS_SCADA] : 'Sécurité des Infrastructures Industrielles (ICS/SCADA)',
  [CATEGORY_EVENT_AND_COMMUNITY] : 'Participation à des Communautés et Événements',
  [CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT_ADVANCED] : 'Gestion des Identités et des Accès Avancés',
  [CATEGORY_ENDPOINTS_SECURITY] : 'Sécurité des Endpoints',
  [CATEGORY_DATA_SECURITY] : 'Sécurité des Données',
  [CATEGORY_NETWORK_SECURITY_ADVANCED] : 'Sécurité des Réseaux Avancée',
  [CATEGORY_SYSTEM_ARCHITECTURE_SECURITY] : 'Sécurité de l’Architecture des Systèmes',
  [CATEGORY_INTERNAL_THREAT_PROTECTION] :'Protection contre les Menaces Internes',
  [CATEGORY_CRISIS_MANAGEMENT] : 'Réponse aux Incidents et Gestion de Crise',
  [CATEGORY_APP_AND_DEVOPS_SECURITY] : 'Sécurité des Applications et des DevOps',
  [CATEGORY_CLOUD_AND_VIRTUAL_ENVIRONMENT_SECURITY] : 'Sécurité des Environnements Virtuels et Cloud',
  [CATEGORY_COMPLIANCE_MANAGEMENT] : 'Gestion de la Conformité et de la Gouvernance',
  [CATEGORY_ATD_ATR] : 'Détection et Réponse aux Menaces Avancées (ATD/ATR)',
  [CATEGORY_SOCIAL_NETWORK_AND_REPUTATION_SECURITY] : 'Sécurité des Réseaux Sociaux et de la Réputation',
  [CATEGORY_FINANCIAL_SECURITY] : 'Sécurité des Transactions Financières',
  [CATEGORY_R_AND_D_SECURITY] : 'Recherche et Développement en Sécurité',
}

const JOB_GENERAL_MANAGER = `JOB_GENERAL_MANAGER`
const JOB_DIGITAL_MANAGER = `JOB_DIGITAL_MANAGER`
const JOB_IT = `JOB_IT`
const JOB_FINANCIAL_MANAGER = `JOB_FINANCIAL_MANAGER`
const JOB_GENERAL_COUNSEL = `JOB_GENERAL_COUNSEL`
const JOB_COMMERCIAL_MANAGER = `JOB_COMMERCIAL_MANAGER`
const JOB_MARKETING_MANAGER = `JOB_MARKETING_MANAGER`
const JOB_STUDENT = `JOB_STUDENT`
const JOB_OTHER = `JOB_OTHER`

const JOBS = {
  [JOB_GENERAL_MANAGER]: `Direction Générale`,
  [JOB_DIGITAL_MANAGER]: `Direction du Digital`,
  [JOB_IT]: `Direction Informatique`,
  [JOB_FINANCIAL_MANAGER]: `Direction Financière`,
  [JOB_GENERAL_COUNSEL]: `Direction Juridique`,
  [JOB_COMMERCIAL_MANAGER]: `Direction Commerciale`,
  [JOB_MARKETING_MANAGER]: `Direction Marketing`,
  [JOB_STUDENT]: `Etudiant`,
  [JOB_OTHER]: `Autres`
}

const COMPANY_SIZE_0_10 = `COMPANY_SIZE_0_10-10`
const COMPANY_SIZE_11_250 = `COMPANY_SIZE_11_250`
const COMPANY_SIZE_251_5000 = `COMPANY_SIZE_251_5000`
const COMPANY_SIZE_5001_PLUS = `COMPANY_SIZE_5001_PLUS`

const COMPANY_SIZE = {
  [COMPANY_SIZE_0_10]:'0-10',
  [COMPANY_SIZE_11_250]:'11-250',
  [COMPANY_SIZE_251_5000]:'251-5000',
  [COMPANY_SIZE_5001_PLUS]:'5001 et plus',
}

const ESTIMATED_DURATION_UNIT_JOURS=`ESTIMATED_DURATION_UNIT_JOURS`
const ESTIMATED_DURATION_UNIT_SEMAINES=`ESTIMATED_DURATION_UNIT_SEMAINES`
const ESTIMATED_DURATION_UNIT_MOIS=`ESTIMATED_DURATION_UNIT_MOIS`

const ESTIMATED_DURATION_UNITS={
  [ESTIMATED_DURATION_UNIT_JOURS]:`jours`,
  [ESTIMATED_DURATION_UNIT_SEMAINES]:`semaines`,
  [ESTIMATED_DURATION_UNIT_MOIS]:`mois`,
}

const LOOKING_FOR_MISSION_YES = 'LOOKING_FOR_MISSION_YES'
const LOOKING_FOR_MISSION_NO = 'LOOKING_FOR_MISSION_NO'

const LOOKING_FOR_MISSION = {
  [LOOKING_FOR_MISSION_YES]: 'oui',
  [LOOKING_FOR_MISSION_NO]: 'non'
}

const CONTENT_PRIVATE = 'CONTENT_PRIVATE'
const CONTENT_PUBLIC = 'CONTENT_PUBLIC'

const CONTENT_VISIBILITY = {
  [CONTENT_PRIVATE]: 'prive',
  [CONTENT_PUBLIC]: 'public'
}

const EVENT_VISIBILITY_PRIVATE = 'EVENT_VISIBILITY_PRIVATE'
const EVENT_VISIBILITY_PUBLIC = 'EVENT_VISIBILITY_PUBLIC'

const EVENT_VISIBILITY = {
  [EVENT_VISIBILITY_PRIVATE]: 'prive',
  [EVENT_VISIBILITY_PUBLIC]: 'public'
}

const ANSWER_YES = 'ANSWER_YES'
const ANSWER_NO = 'ANSWER_NO'
const ANSWER_NOT_APPLICABLE = 'ANSWER_NOT_APPLICABLE'

const ANSWERS = {
  [ANSWER_YES] : 'oui',
  [ANSWER_NO]  : 'non',
  [ANSWER_NOT_APPLICABLE] : 'N\\A'
}

module.exports = {
  DISC_ADMIN, DISC_MEMBER, DISC_PARTNER, DISCRIMINATOR_KEY,
  ROLES, ROLE_ADMIN, ROLE_MEMBER, ROLE_PARTNER,
  CONTENT_TYPE, CONTENT_TYPE_ARTICLE, CONTENT_TYPE_GUIDE, CONTENT_TYPE_PODCAST, CONTENT_TYPE_VIDEO,
  SECTOR,
  CATEGORIES, CATEGORY_THREAT_ANALYSIS, CATEGORY_NETWORK_SECURITY, CATEGORY_CRYPTOGRAPHY, CATEGORY_APP_SECURITY, CATEGORY_FORENSIC, CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT, CATEGORY_CONFORMITY_AND_CONTROL, CATEGORY_CLOUD_SECURITY, CATEGORY_SYSTEM_SECURITY, CATEGORY_SENSITIZATION_AND_FORMATION, CATEGORY_EMERGING_SAFETY_TECHNOLOGIES, CATEGORY_INCIDENT_MANAGEMENT, CATEGORY_SECURITY_POLICY_DESIGN, CATEGORY_ICS_SCADA, CATEGORY_EVENT_AND_COMMUNITY, CATEGORY_ACCESS_AND_IDENTITY_MANAGEMENT_ADVANCED, CATEGORY_ENDPOINTS_SECURITY, CATEGORY_DATA_SECURITY, CATEGORY_NETWORK_SECURITY_ADVANCED, CATEGORY_SYSTEM_ARCHITECTURE_SECURITY, CATEGORY_INTERNAL_THREAT_PROTECTION, CATEGORY_CRISIS_MANAGEMENT, CATEGORY_APP_AND_DEVOPS_SECURITY, CATEGORY_CLOUD_AND_VIRTUAL_ENVIRONMENT_SECURITY, CATEGORY_COMPLIANCE_MANAGEMENT, CATEGORY_ATD_ATR, CATEGORY_SOCIAL_NETWORK_AND_REPUTATION_SECURITY, CATEGORY_FINANCIAL_SECURITY, CATEGORY_R_AND_D_SECURITY,
  JOBS, JOB_GENERAL_MANAGER, JOB_DIGITAL_MANAGER, JOB_IT, JOB_FINANCIAL_MANAGER, JOB_GENERAL_COUNSEL, JOB_COMMERCIAL_MANAGER, JOB_MARKETING_MANAGER, JOB_STUDENT, JOB_OTHER,
  COMPANY_SIZE, ESTIMATED_DURATION_UNITS, ESTIMATED_DURATION_UNIT_JOURS, ESTIMATED_DURATION_UNIT_SEMAINES, ESTIMATED_DURATION_UNIT_MOIS, LOOKING_FOR_MISSION, LOOKING_FOR_MISSION_YES, LOOKING_FOR_MISSION_NO, CONTENT_VISIBILITY, CONTENT_PRIVATE, CONTENT_PUBLIC, EVENT_VISIBILITY, EVENT_VISIBILITY_PRIVATE, EVENT_VISIBILITY_PUBLIC,
  ANSWERS, ANSWER_NO, ANSWER_NOT_APPLICABLE, ANSWER_YES
}