const VISIO_STATUS_UNDEFINED=`VISIO_STATUS_UNDEFINED`
const VISIO_STATUS_TO_COME=`VISIO_STATUS_TO_COME`
const VISIO_STATUS_CURRENT=`VISIO_STATUS_CURRENT`
const VISIO_STATUS_FINISHED=`VISIO_STATUS_FINISHED`

const VISIO_STATUS={
  [VISIO_STATUS_UNDEFINED]:`A définir`,
  [VISIO_STATUS_TO_COME]:`A venir`,
  [VISIO_STATUS_CURRENT]:`En cours`,
  [VISIO_STATUS_FINISHED]:`Terminée`,
}

module.exports={
  VISIO_STATUS, VISIO_STATUS_CURRENT, VISIO_STATUS_FINISHED, VISIO_STATUS_TO_COME, VISIO_STATUS_UNDEFINED
}