const nationalities=require('i18n-nationality')

const SOSYNPL=`So SynpL`

// Discirimnator for User/Admin/Customer/Freelance
const DISCRIMINATOR_KEY = { discriminatorKey: 'type' }
const DISC_CUSTOMER='customer'
const DISC_FREELANCE='freelance'
const DISC_ADMIN='admin'


const ROLE_CUSTOMER=`CUSTOMER`
const ROLE_FREELANCE=`FREELANCE`
const ROLE_ADMIN=`ADMIN`

const ROLES={
  [ROLE_CUSTOMER]:`Client`,
  [ROLE_FREELANCE]:`Freelance`,
  [ROLE_ADMIN]:`Administrateur`,
}

const NATIONALITIES=nationalities.getNames('fr')

const COMPANY_SIZE_LESS_10=`COMPANY_SIZE_LESS_10`
const COMPANY_SIZE__11__250=`COMPANY_SIZE__11__250`
const COMPANY_SIZE__251_5000=`COMPANY_SIZE__251_5000`
const COMPANY_SIZE_MORE_5001=`COMPANY_SIZE_MORE_5001`

const COMPANY_SIZE={
  [COMPANY_SIZE_LESS_10]:`< 10`,
  [COMPANY_SIZE__11__250]:`11 - 250`,
  [COMPANY_SIZE__251_5000]:`251 - 5000`,
  [COMPANY_SIZE_MORE_5001]:`> 500`,
}

const WORK_MODE_REMOTE=`WORK_MODE_REMOTE`
const WORK_MODE_SITE=`WORK_MODE_SITE`
const WORK_MODE_REMOTE_SITE=`WORK_MODE_REMOTE_SITE`

const WORK_MODE={
  [WORK_MODE_REMOTE]:`À distance`,
  [WORK_MODE_SITE]:`Sur site`,
  [WORK_MODE_REMOTE_SITE]:`À distance & sur site`,
}

const WORK_DURATION_LESS_1_MONTH=`WORK_DURATION_LESS_1_MONTH`
const WORK_DURATION__1_TO_6_MONTHS=`WORK_DURATION__1_TO_6_MONTHS`
const WORK_DURATION_MORE_6_MONTH=`WORK_DURATION_MORE_6_MONTH`

const WORK_DURATION={
  [WORK_DURATION_LESS_1_MONTH]:`< 1 mois`,
  [WORK_DURATION__1_TO_6_MONTHS]:`1 à 6 mois`,
  [WORK_DURATION_MORE_6_MONTH]:`> 6 mois`,
}

const VALID_STATUS_PENDING=`VALID_STATUS_PENDING`
const VALID_STATUS_ACEEPTED=`VALID_STATUS_ACEEPTED`
const VALID_STATUS_REFUSED=`VALID_STATUS_REFUSED`

const VALID_STATUS={
  [VALID_STATUS_PENDING]:`En attente`,
  [VALID_STATUS_ACEEPTED]:`Accepté`,
  [VALID_STATUS_REFUSED]:`Refusé`,
}

const SOURCE_RECOMMANDATION=`SOURCE_RECOMMANDATION`
const SOURCE_SOSYNPL_CONTACT=`SOURCE_SOSYNPL_CONTACT`
const SOURCE_EVENT=`SOURCE_EVENT`
const SOURCE_SOCIAL_NETWORK=`SOURCE_SOCIAL_NETWORK`
const SOURCE_NEWS_BLOG=`SOURCE_NEWS_BLOG`
const SOURCE_OTHER=`SOURCE_OTHER`

const SOURCE={
  [SOURCE_RECOMMANDATION]:`Recommandation`,
  [SOURCE_SOSYNPL_CONTACT]:`Contacté par SoSynpL`,
  [SOURCE_EVENT]:`Evénement`,
  [SOURCE_SOCIAL_NETWORK]:`Réseaux sociaux`,
  [SOURCE_NEWS_BLOG]:`Blogs/news`,
  [SOURCE_OTHER]:`Autre`,
}

const EXPERIENCE_JUNIOR=`EXPERIENCE_JUNIOR`
const EXPERIENCE_EXPERIMENTED=`EXPERIENCE_EXPERIMENTED`
const EXPERIENCE_SENIOR=`EXPERIENCE_SENIOR`
const EXPERIENCE_EXPERT=`EXPERIENCE_EXPERT`

const EXPERIENCE={
  [EXPERIENCE_JUNIOR]:`Junior: < 2 ans`,
  [EXPERIENCE_EXPERIMENTED]:`Expérimenté : 3-5 ans`,
  [EXPERIENCE_SENIOR]:`Senior : 6-9 ans`,
  [EXPERIENCE_EXPERT]:`Expert : 10 ans et plus`,
}

const LEGAL_STATUS_EI=`EI`
const LEGAL_STATUS_EURL=`EURL`
const LEGAL_STATUS_SARL=`SARL`
const LEGAL_STATUS_SA=`SA`
const LEGAL_STATUS_SAS=`SAS`
const LEGAL_STATUS_SASU=`SASU`
const LEGAL_STATUS_SNC=`SNC`
const LEGAL_STATUS_SCOP=`SCOP`
const LEGAL_STATUS_SCA=`SCA`
const LEGAL_STATUS_SCS=`SCS`
const LEGAL_STATUS_1901=`1901`
const LEGAL_STATUS_CIVIL=`CIVIL`
const LEGAL_STATUS_SEP=`SEP`
const LEGAL_STATUS_SCIC=`SCIC`
const LEGAL_STATUS_PORTAGE=`PORTAGE`
const LEGAL_STATUS_INCUBATOR=`INCUBATOR`
const LEGAL_STATUS_CAE=`CAE`
const LEGAL_STATUS_MDA=`MDA`
const LEGAL_STATUS_PUBLIC=`PUBLIC`

const LEGAL_STATUS={
  [LEGAL_STATUS_EI]:`EI - Entreprise individuelle ou micro-entreprise`,
  [LEGAL_STATUS_EURL]:`EURL - Entreprise unipersonnelle à responsabilité limitée`,
  [LEGAL_STATUS_SARL]:`SARL - Société à responsabilité limitée`,
  [LEGAL_STATUS_SA]:`SA - Société anonyme`,
  [LEGAL_STATUS_SAS]:`SAS - Société par actions simplifiée`,
  [LEGAL_STATUS_SASU]:`SASU - Société par actions simplifiée unipersonnelle`,
  [LEGAL_STATUS_SNC]:`SNC - Société en nom collectif`,
  [LEGAL_STATUS_SCOP]:`Scop - Société coopérative de production`,
  [LEGAL_STATUS_SCA]:`SCA - Société en commandite par actions`,
  [LEGAL_STATUS_SCS]:`SCS - Société en commandite simple`,
  [LEGAL_STATUS_1901]:`Association loi 1901`,
  [LEGAL_STATUS_CIVIL]:`Société civile`,
  [LEGAL_STATUS_SEP]:`SEP - société en participation`,
  [LEGAL_STATUS_SCIC]:`SCIC - Société coopérative d'intérêt collectif`,
  [LEGAL_STATUS_PORTAGE]:`Société de portage salarial`,
  [LEGAL_STATUS_INCUBATOR]:`Couveuses d'entreprises (société)`,
  [LEGAL_STATUS_CAE]:`CAE - Coopérative d'activités et d'emploi`,
  [LEGAL_STATUS_MDA]:`MDA/ Agessa`,
  [LEGAL_STATUS_PUBLIC]:`Entreprise publique`,
}

const REASON_NOT_FREELANCE=`REASON_NOT_FREELANCE`
const REASON_NO_NEED=`REASON_NO_NEED`
const REASON_NOT_SATISFIED=`REASON_NOT_SATISFIED`
const REASON_OTHER=`REASON_OTHER`

const DEACTIVATION_REASON={
  [REASON_NOT_FREELANCE]:`Je ne suis plus indépendant`,
  [REASON_NO_NEED]:`Je n’ai plus besoin du service de So SynpL`,
  [REASON_NOT_SATISFIED]:`Je ne suis pas satisfait du service de So SynpL`,
  [REASON_OTHER]:`Autre`,
}

const SUSPEND_REASON_INACTIVE=`Compte inactif`
const SUSPEND_REASON_CRITERION=`Ne corespond pas à la charte de So SynpL`
const SUSPEND_REASON_OTHER=`SUSPEND_REASON_OTHER`

const SUSPEND_REASON={
  [SUSPEND_REASON_INACTIVE]: `Compte inactif`,
  [SUSPEND_REASON_CRITERION]: `Ne corespond pas à la charte de So SynpL`,
  [SUSPEND_REASON_OTHER]: `Autre`,
}

const SUSPEND_STATE_SUSPENDED=`SUSPEND_STATE_SUSPENDED`
const SUSPEND_STATE_NOT_SUSPENDED=`SUSPEND_STATE_NOT_SUSPENDED`
const SUSPEND_STATE_STANDBY=`SUSPEND_STATE_STANDBY`

const SUSPEND_STATE={
  [SUSPEND_STATE_SUSPENDED]:`Suspendu`,
  [SUSPEND_STATE_NOT_SUSPENDED]:`Non suspendu`,
  [SUSPEND_STATE_STANDBY]:`A définir`,
}

module.exports={
  SOSYNPL, ROLES, NATIONALITIES, COMPANY_SIZE, WORK_MODE, WORK_DURATION, VALID_STATUS, VALID_STATUS_PENDING, SOURCE,
  DISCRIMINATOR_KEY, DISC_CUSTOMER, DISC_FREELANCE, DISC_ADMIN, EXPERIENCE, ROLE_CUSTOMER, ROLE_FREELANCE,
  LEGAL_STATUS, DEACTIVATION_REASON, SUSPEND_REASON, SUSPEND_STATE, SUSPEND_STATE_NOT_SUSPENDED, SUSPEND_STATE_STANDBY,
  SUSPEND_STATE_SUSPENDED,
}

