const nationalities=require('i18n-nationality')

const SOSYNPL=`So SynpL`

// Discirimnator for User/Admin/Customer/Freelance
const DISCRIMINATOR_KEY = { discriminatorKey: 'type' }
const DISC_CUSTOMER='customer'
const DISC_FREELANCE='freelance'
const DISC_ADMIN='admin'


const ROLE_CUSTOMER=`CUSTOMER`
const ROLE_FREELANCE=`FREELANCE`
const ROLE_ADMIN=`ADMIN`

const ROLES={
  [ROLE_CUSTOMER]:`Client`,
  [ROLE_FREELANCE]:`Freelance`,
  [ROLE_ADMIN]:`Administrateur`,
}

const NATIONALITIES=nationalities.getNames('fr')

const COMPANY_SIZE_LESS_10=`COMPANY_SIZE_LESS_10`
const COMPANY_SIZE__11__250=`COMPANY_SIZE__11__250`
const COMPANY_SIZE__251_5000=`COMPANY_SIZE__251_5000`
const COMPANY_SIZE_MORE_5001=`COMPANY_SIZE_MORE_5001`

const COMPANY_SIZE={
  [COMPANY_SIZE_LESS_10]:`< 10`,
  [COMPANY_SIZE__11__250]:`11 - 250`,
  [COMPANY_SIZE__251_5000]:`251 - 5000`,
  [COMPANY_SIZE_MORE_5001]:`> 500`,
}

const WORK_MODE_REMOTE=`WORK_MODE_REMOTE`
const WORK_MODE_SITE=`WORK_MODE_SITE`
const WORK_MODE_REMOTE_SITE=`WORK_MODE_REMOTE_SITE`

const WORK_MODE={
  [WORK_MODE_REMOTE]:`À distance`,
  [WORK_MODE_SITE]:`Sur site`,
  [WORK_MODE_REMOTE_SITE]:`À distance & sur site`,
}

const WORK_DURATION_LESS_1_MONTH=`WORK_DURATION_LESS_1_MONTH`
const WORK_DURATION__1_TO_6_MONTHS=`WORK_DURATION__1_TO_6_MONTHS`
const WORK_DURATION_MORE_6_MONTH=`WORK_DURATION_MORE_6_MONTH`

const WORK_DURATION={
  [WORK_DURATION_LESS_1_MONTH]:`< 1 mois`,
  [WORK_DURATION__1_TO_6_MONTHS]:`1 à 6 mois`,
  [WORK_DURATION_MORE_6_MONTH]:`> 6 mois`,
}

const VALID_STATUS_PENDING=`VALID_STATUS_PENDING`
const VALID_STATUS_ACEEPTED=`VALID_STATUS_ACEEPTED`
const VALID_STATUS_REFUSED=`VALID_STATUS_REFUSED`

const VALID_STATUS={
  [VALID_STATUS_PENDING]:`En attente`,
  [VALID_STATUS_ACEEPTED]:`Accepté`,
  [VALID_STATUS_REFUSED]:`Refusé`,
}

const SOURCE_RECOMMANDATION=`SOURCE_RECOMMANDATION`
const SOURCE_SOSYNPL_CONTACT=`SOURCE_SOSYNPL_CONTACT`
const SOURCE_EVENT=`SOURCE_EVENT`
const SOURCE_SOCIAL_NETWORK=`SOURCE_SOCIAL_NETWORK`
const SOURCE_NEWS_BLOG=`SOURCE_NEWS_BLOG`
const SOURCE_OTHER=`SOURCE_OTHER`

const SOURCE={
  [SOURCE_RECOMMANDATION]:`Recommandation`,
  [SOURCE_SOSYNPL_CONTACT]:`Contacté par SoSynpL`,
  [SOURCE_EVENT]:`Evénement`,
  [SOURCE_SOCIAL_NETWORK]:`Réseaux sociaux`,
  [SOURCE_NEWS_BLOG]:`Blogs/news`,
  [SOURCE_OTHER]:`Autre`,
}

const EXPERIENCE_JUNIOR=`EXPERIENCE_JUNIOR`
const EXPERIENCE_EXPERIMENTED=`EXPERIENCE_EXPERIMENTED`
const EXPERIENCE_SENIOR=`EXPERIENCE_SENIOR`
const EXPERIENCE_EXPERT=`EXPERIENCE_EXPERT`

const EXPERIENCE={
  [EXPERIENCE_JUNIOR]:`Junior: < 2 ans`,
  [EXPERIENCE_EXPERIMENTED]:`Expérimenté : 3-5 ans`,
  [EXPERIENCE_SENIOR]:`Senior : 6-9 ans`,
  [EXPERIENCE_EXPERT]:`Expert : 10 ans et plus`,
}

module.exports={
  SOSYNPL, ROLES, NATIONALITIES, COMPANY_SIZE, WORK_MODE, WORK_DURATION, VALID_STATUS, VALID_STATUS_PENDING, SOURCE,
  DISCRIMINATOR_KEY, DISC_CUSTOMER, DISC_FREELANCE, DISC_ADMIN, EXPERIENCE, ROLE_CUSTOMER, ROLE_FREELANCE,
}

