const ROLE_APPRENANT="APPRENANT"
const ROLE_FORMATEUR="FORMATEUR"
const ROLE_CONCEPTEUR="CONCEPTEUR"
const ROLE_GESTIONNAIRE="GESTIONNAIRE"
const ROLE_SUPERVISEUR="SUPERVISEUR"
const ROLE_HELPDESK="HELPDESK"
const ROLE_ADMINISTRATEUR="ADMINISTRATEUR"

const ROLES={
  [ROLE_APPRENANT]:"Apprenant",
  [ROLE_FORMATEUR]:"Formateur",
  [ROLE_CONCEPTEUR]:"Concepteur",
  [ROLE_GESTIONNAIRE]:"Gestionnaire",
  [ROLE_SUPERVISEUR]:"Superviseur",
  [ROLE_HELPDESK]:"Helpdesk",
  [ROLE_ADMINISTRATEUR]:"Administrateur",
}

module.exports={
    ROLES,
}