const ROLE_APPRENANT="ROLE_APPRENANT"
const ROLE_FORMATEUR="ROLE_FORMATEUR"
const ROLE_CONCEPTEUR="ROLE_CONCEPTEUR"
const ROLE_GESTIONNAIRE="ROLE_GESTIONNAIRE"
const ROLE_SUPERVISEUR="ROLE_SUPERVISEUR"
const ROLE_HELPDESK="ROLE_HELPDESK"
const ROLE_ADMINISTRATEUR="ROLE_ADMINISTRATEUR"

const ROLES={
  [ROLE_APPRENANT]:"apprenant",
  [ROLE_FORMATEUR]:"formateur",
  [ROLE_CONCEPTEUR]:"concepteur",
  [ROLE_GESTIONNAIRE]:"gestionnaire",
  [ROLE_SUPERVISEUR]:"superviseur",
  [ROLE_HELPDESK]:"helpdesk",
  [ROLE_ADMINISTRATEUR]:"administrateur",
}

module.exports={
    ROLES,
}