# Rule the world

## Java

On commence l'ascension en installant la `version 11 of the Java SE Development Kit (JDK)``

## Android Studio

* Installer Android Studio 😅, avec les éléments suivants :

📦 Android SDK
📦 Android SDK Platform
📦 Android Virtual Device

Puis, créer un device, Pixel 4a par exemple, avec l'api level en 31 (RN recommandation), qui vient accompagné de `Intel x86 Atom_64 System Image`.

## Config React Native

### ENV VAR

ref : https://reactnative.dev/docs/environment-setup

Inscrire les variables d'environnement ANDROID_HOME dans son .bash_profile, ou .bashrc

[code, config]
----
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
----

### Watchman (hautement recommandé, mais je l'ai pas mis)

Outil de Facebook qui scrute tous les changements de fichiers.

## Expo

Expo, c'est un peu le framework qui est là, pour la magie ✨

IMPORTANT: Attention, installer spécialement cette version.
Une plus récente forcerait le build par eas-cli qui impose la création d'un compte chez eas.
[code, bash]
----
npm install -g expo-cli@6.0.8
----

## C'est quand qu'on build ?

Quelques fichiers à modifier

[source, pro]
.studio-test-native/apps/expo/android/app/proguard-rules.pro
----
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Add any project specific keep options here:

# Add hermes support by adding these two lines
-keep class com.facebook.hermes.unicode.** { *; }
-keep class com.facebook.jni.** { *; }
----


[source, properties]
.studio-test-native/apps/expo/android/gradle.properties
----
...
# define hermes
expo.jsEngine=hermes
...
----


[source, gradle]
.studio-test-native/apps/expo/android/settings.gradle
----
rootProject.name = 'NAME_PROJECT'

apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");
useExpoModules()

apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'
includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())

if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
  include(":ReactAndroid")
  project(":ReactAndroid").projectDir = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../ReactAndroid");
  include(":ReactAndroid:hermes-engine")
  project(":ReactAndroid:hermes-engine").projectDir = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../ReactAndroid/hermes-engine");
}

----

🏎 Gentlemen, start your engines. Après tout, on est là pour ça. Faut que ça sorte.

* Se rendre dans `studio-test-native/apps/expo`
* expo run:android pour builder => dossier android puis démarrer


Les sources sont là, dans le dossier `android`, pour aller jouer avec.


## SDK Withings

Quelques permissions nécessaires pour le SDK withings

[source, xml]
.studio-test-native/apps/expo/android/app/src/main/AndroidManifest.xml
----
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.pasquiou.testapp">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />


  ...
----




## Divers

C'est déjà beau d'être arrivé jusqu'ici.

### jlink manque à l'appel ?

La réponse https://stackoverflow.com/questions/73107234/how-to-fix-jlink-does-not-exist#answer-73146019

## Customisation

### Icône de l'application
Générer avec l'excellent outil https://icon.kitchen !!
Puis dézipper et copier sour apps/expo/android/app/src/main/res
